//
//  Server.swift
//  mul-api
//
//  Created by Richard Hancock on 5/9/25.
//

/// Defines the ``MegaMek/Server`` Fluent model: a record of a live MegaMek game-server
/// instance that has "announced" itself to this API (see `ServersController` and
/// `Api.V1.ServersController`), so the announcement can be listed publicly (e.g. an
/// in-game server browser).

import Fluent
import Vapor

extension MegaMek {
    /// A Fluent database model representing one announced MegaMek server instance:
    /// its network address, whether it's password-protected, connected users, and version.
    ///
    /// `@Field` maps a required stored column; `@OptionalField` maps a nullable one;
    /// `@Timestamp` auto-manages a date column on create/update. `Content` lets this model
    /// be encoded/decoded directly as JSON by Vapor for the read-only listing endpoints.
    final class Server: Model, Content, @unchecked Sendable {
        public static let schema: String = MegaMek.Server.V20250509.schemaName
        public static let space: String? = MegaMek.Server.V20250509.spaceName

        @ID
        var id: UUID?

        // Network location the server is reachable at, and whether it requires a password.
        @Field(key: MegaMek.Server.V20250509.port)
        var port: Int

        @Field(key: MegaMek.Server.V20250509.ipAddress)
        var ipAddress: String

        @Field(key: MegaMek.Server.V20250509.passworded)
        var passworded: Bool

        // Connected users (stored as a single comma-separated string, not a JSON array),
        // and a secret key the announcing client can present later to update this same
        // record instead of creating a duplicate.
        @Field(key: MegaMek.Server.V20250509.users)
        var users: String

        @Field(key: MegaMek.Server.V20250509.serverKey)
        var serverKey: String

        // Game/server version, current game phase, and an optional message-of-the-day.
        @Field(key: MegaMek.Server.V20250509.version)
        var version: String

        @Field(key: MegaMek.Server.V20250509.phase)
        var phase: String

        @OptionalField(key: MegaMek.Server.V20250509.motd)
        var motd: String?

        @Timestamp(key: MegaMek.Server.V20250509.createdAt, on: .create)
        var createdAt: Date?

        @Timestamp(key: MegaMek.Server.V20250509.updatedAt, on: .update)
        var updatedAt: Date?

        /// Empty initializer required by Fluent so it can hydrate instances from the database.
        init() {}

        /// Creates a new server announcement record and generates a fresh random
        /// `serverKey` (a 16-byte, base64url-encoded secret) that the client can use on
        /// subsequent announcements to update this same record rather than create a new one.
        /// - Parameters:
        ///   - id: Optional pre-assigned identifier; normally left `nil` and generated by the database.
        ///   - port: The port the game server is listening on; defaults to MegaMek's standard `2346`.
        ///   - ipAddress: The IP address the server is reachable at.
        ///   - passworded: Whether the server requires a password to join; defaults to `false`.
        ///   - users: Comma-separated list of connected usernames; defaults to empty.
        ///   - version: The MegaMek version string the server is running.
        ///   - phase: The current game phase.
        ///   - motd: Optional message-of-the-day text.
        init(
            id: UUID? = nil,
            port: Int = 2346,
            ipAddress: String,
            passworded: Bool = false,
            users: String = "",
            version: String,
            phase: String,
            motd: String? = nil
        ) {
            self.id = id
            self.port = port
            self.ipAddress = ipAddress
            self.passworded = passworded
            self.users = users
            self.version = version
            self.phase = phase
            self.motd = motd

            self.serverKey = [UInt8].random(count: 16).base64.base64URLSafe()
        }
    }
}
