//
//  ConfirmationToken.swift
//
//  Confirmation Token storage for Users
//
//  Created by Richard Hancock on 3/16/23.
//

/// Defines the ``Security/ConfirmationToken`` Fluent model, used to verify a user's email
/// address (initial signup, or a subsequent email-address change) via a one-time link.
///
/// Also provides the `generate(for:)` factory and an `isValid` expiry check.

import Fluent
import Vapor

extension Security {
    /// A Fluent database model (an ORM record backed by a table) representing a single-use
    /// email confirmation token issued to a ``Security/User``.
    ///
    /// `@Field`/`@Parent`/`@Timestamp` are Fluent property wrappers: `@Field` maps a stored
    /// column, `@Parent` declares a belongs-to relationship (here, the user the token was
    /// issued for), and `@Timestamp` auto-manages a date column (here, set once on creation).
    /// `Content` lets this model be encoded/decoded directly as JSON by Vapor.
    final class ConfirmationToken: Model, Content, @unchecked Sendable {
        public static let schema: String = Security.ConfirmationToken.V20230316.schemaName
        public static let space: String? = Security.ConfirmationToken.V20230316.spaceName

        @ID
        var id: UUID?

        // The random token value sent to the user, and the user it was issued for.
        @Field(key: Security.ConfirmationToken.V20230316.value)
        var value: String

        @Parent(key: Security.ConfirmationToken.V20230316.userID)
        var user: User

        @Timestamp(key: Security.User.V20221227.createdAt, on: .create)
        var createdAt: Date?

        /// Empty initializer required by Fluent so it can hydrate instances from the database.
        init() {}

        /// Creates a token record in memory (not yet persisted) with an explicit value and
        /// owning user ID.
        /// - Parameters:
        ///   - id: Optional pre-assigned identifier; normally left `nil` and generated by the database.
        ///   - value: The random token string that will be sent to the user.
        ///   - userID: The identifier of the ``Security/User`` this token confirms.
        init(id: UUID? = nil, value: String, userID: User.IDValue) {
            self.id = id
            self.value = value
            self.$user.id = userID
        }
    }
}

extension Security.ConfirmationToken {
    /// Generates a fresh confirmation token for the given user: a cryptographically random
    /// 32-byte value, base64url-encoded, that is not yet saved to the database.
    /// - Parameter user: The ``Security/User`` the token will confirm; must already have an ID.
    /// - Returns: A new, unsaved ``Security/ConfirmationToken``.
    /// - Throws: If `user` has no assigned ID yet.
    static func generate(for user: Security.User) throws -> Security.ConfirmationToken {
        let random = [UInt8].random(count: 32).base64.base64URLSafe()
        return try Security.ConfirmationToken(value: random, userID: user.requireID())
    }

    /// Whether this token is still usable. Confirmation tokens expire 72 hours after
    /// creation; past that window this returns `false` and the token should be rejected.
    var isValid: Bool {
        if let date = Calendar.current.date(byAdding: .hour, value: -72, to: Date()),
           let createdDate = self.createdAt,
           createdDate < date
        {
            return false
        } else {
            return true
        }
    }
}
