//
//  ForgotPasswordToken.swift
//
//  Forgot Password Token storage for Users
//
//  Created by Richard Hancock on 3/12/23.
//

/// Defines the ``Security/ForgotPasswordToken`` Fluent model, used to authorize a
/// password-reset request via a one-time link emailed to the user.
///
/// Also provides the `generate(for:)` factory and an `isValid` expiry check.

import Fluent
import Vapor

extension Security {
    /// A Fluent database model representing a single-use password-reset token issued to a
    /// ``Security/User``.
    ///
    /// `@Field`/`@Parent`/`@Timestamp` are Fluent property wrappers: `@Field` maps a stored
    /// column, `@Parent` declares a belongs-to relationship (here, the user requesting the
    /// reset), and `@Timestamp` auto-manages a date column (here, set once on creation).
    /// `Content` lets this model be encoded/decoded directly as JSON by Vapor.
    final class ForgotPasswordToken: Model, Content, @unchecked Sendable {
        public static let schema: String = Security.ForgotPasswordToken.V20230312.schemaName
        public static let space: String? = Security.ForgotPasswordToken.V20230312.spaceName

        @ID
        var id: UUID?

        // The random token value sent to the user, and the user requesting the reset.
        @Field(key: Security.ForgotPasswordToken.V20230312.value)
        var value: String

        @Parent(key: Security.ForgotPasswordToken.V20230312.userID)
        var user: User

        @Timestamp(key: Security.User.V20221227.createdAt, on: .create)
        var createdAt: Date?

        /// Empty initializer required by Fluent so it can hydrate instances from the database.
        init() {}

        /// Creates a token record in memory (not yet persisted) with an explicit value and
        /// owning user ID.
        /// - Parameters:
        ///   - id: Optional pre-assigned identifier; normally left `nil` and generated by the database.
        ///   - value: The random token string that will be sent to the user.
        ///   - userID: The identifier of the ``Security/User`` requesting the reset.
        init(id: UUID? = nil, value: String, userID: User.IDValue) {
            self.id = id
            self.value = value
            self.$user.id = userID
        }
    }
}

extension Security.ForgotPasswordToken {
    /// Generates a fresh password-reset token for the given user: a cryptographically
    /// random 24-byte value, base64url-encoded, that is not yet saved to the database.
    /// - Parameter user: The ``Security/User`` requesting the reset; must already have an ID.
    /// - Returns: A new, unsaved ``Security/ForgotPasswordToken``.
    /// - Throws: If `user` has no assigned ID yet.
    static func generate(for user: Security.User) throws -> Security.ForgotPasswordToken {
        let random = [UInt8].random(count: 24).base64.base64URLSafe()
        return try Security.ForgotPasswordToken(value: random, userID: user.requireID())
    }

    /// Whether this token is still usable. Password-reset tokens expire 1 hour after
    /// creation (much shorter than confirmation tokens, since a leaked reset link is more
    /// immediately dangerous); past that window this returns `false` and the token should
    /// be rejected.
    var isValid: Bool {
        if let date = Calendar.current.date(byAdding: .hour, value: -1, to: Date()),
           let createdDate = self.createdAt,
           createdDate < date
        {
            return false
        } else {
            return true
        }
    }
}
