//
//  Token.swift
//
//  Token storage for Users
//
//  Created by Richard Hancock on 1/19/23.
//

/// Defines the ``Security/Token`` Fluent model: the bearer authentication token issued to a
/// ``Security/User`` after login and presented on subsequent requests (e.g. as an
/// `Authorization: Bearer <value>` header) instead of resending credentials.

import Fluent
import Vapor

extension Security {
    /// A Fluent database model representing a session/API bearer token belonging to a
    /// ``Security/User``.
    ///
    /// `@Field`/`@Parent`/`@Timestamp` are Fluent property wrappers: `@Field` maps a stored
    /// column, `@Parent` declares a belongs-to relationship (here, the authenticated user),
    /// and `@Timestamp` auto-manages a date column (here, set once on creation). `Content`
    /// lets this model be encoded/decoded directly as JSON by Vapor.
    final class Token: Model, Content, @unchecked Sendable {
        public static let schema: String = Security.Token.V20230119.schemaName
        public static let space: String? = Security.Token.V20230119.spaceName

        @ID
        var id: UUID?

        // The token's secret value, and the user it authenticates as.
        @Field(key: Security.Token.V20230119.value)
        var value: String

        @Parent(key: Security.Token.V20230119.userID)
        var user: User

        @Timestamp(key: Security.User.V20221227.createdAt, on: .create)
        var createdAt: Date?

        /// Empty initializer required by Fluent so it can hydrate instances from the database.
        init() {}

        /// Creates a token record in memory (not yet persisted) with an explicit value and
        /// owning user ID.
        /// - Parameters:
        ///   - id: Optional pre-assigned identifier; normally left `nil` and generated by the database.
        ///   - value: The secret bearer-token string.
        ///   - userID: The identifier of the ``Security/User`` this token authenticates as.
        init(id: UUID? = nil, value: String, userID: User.IDValue) {
            self.id = id
            self.value = value
            self.$user.id = userID
        }
    }
}

extension Security.Token {
    /// Generates a fresh bearer token for the given user: a cryptographically random
    /// 16-byte value, base64url-encoded, that is not yet saved to the database. Typically
    /// called right after a successful login to hand back to the client.
    /// - Parameter user: The ``Security/User`` to issue the token for; must already have an ID.
    /// - Returns: A new, unsaved ``Security/Token``.
    /// - Throws: If `user` has no assigned ID yet.
    static func generate(for user: User) throws -> Security.Token {
        let random = [UInt8].random(count: 16).base64.base64URLSafe()
        return try Security.Token(value: random, userID: user.requireID())
    }
}

/// Conformance to Vapor's `ModelTokenAuthenticatable`, which wires this model into Vapor's
/// bearer-token authentication middleware: given a token value from an incoming request,
/// Vapor looks up the matching `Security.Token` row and, if `isValid`, authenticates the
/// associated ``Security/User`` for that request.
extension Security.Token: ModelTokenAuthenticatable {
    /// Key path telling Vapor which field holds the raw token value to match against.
    static var valueKey: KeyPath<Security.Token, Field<String>> {
        \Security.Token.$value
    }

    /// Key path telling Vapor which relationship holds the authenticated user.
    static var userKey: KeyPath<Security.Token, Parent<Security.User>> {
        \Security.Token.$user
    }

    typealias User = App.Security.User

    /// Whether this token is still usable. Tokens expire 14 days after creation; past that
    /// window this returns `false` and Vapor's authentication middleware will reject it,
    /// requiring the user to log in again.
    var isValid: Bool {
        if let date = Calendar.current.date(byAdding: .day, value: -14, to: Date()),
           let createdDate = self.createdAt,
           createdDate < date
        {
            return false
        } else {
            return true
        }
    }
}
