//
//  User.swift
//
//  User model
//
//  Created by Richard Hancock on 12/27/22.
//

/// Defines the ``Security/User`` Fluent model (the core account/authentication record),
/// its error type, and two public-facing views of a user (``Security/User/Profile`` and
/// ``Security/User/Public``) used to avoid ever serializing sensitive fields like the
/// password hash directly over the API.

import Fluent
import Vapor

extension Security {
    /// Errors surfaced by user account operations (password changes, role changes,
    /// activation state, email confirmation), each with a human-readable description
    /// suitable for returning in an API error response.
    enum UserError: Error, LocalizedError {
        case passwordsDoNotMatch
        case cantModifyAdminAsAnAdmin
        case userNotActive
        case cantEmailUnconfirmedWithoutEmailAddress

        public var errorDescription: String? {
            switch self {
            case .passwordsDoNotMatch:
                return "Passwords Do Not Match"

            case .cantModifyAdminAsAnAdmin:
                return "For safety, can't change the role of an admin as an admin."

            case .userNotActive:
                return "User is not currently active."

            case .cantEmailUnconfirmedWithoutEmailAddress:
                return "Unable to send an email to an unconfirmed address with an unconfirmed email"
            }
        }
    }

    /// A Fluent database model representing a registered account: credentials, contact
    /// info, role, and confirmation/audit timestamps.
    ///
    /// `@Field` maps a required stored column; `@OptionalField` maps a nullable one;
    /// `@Timestamp` auto-manages a date column on a lifecycle event (`.create`, `.update`,
    /// or `.delete`, the last enabling Fluent's soft-delete behavior). `Content` lets this
    /// model be encoded/decoded directly as JSON by Vapor — note that doing so naively
    /// would expose the `password` hash, which is why ``Security/User/Public`` and
    /// ``Security/User/Profile`` exist as safer response shapes (see below).
    final class User: Model, Content, @unchecked Sendable {
        public static let schema: String = Security.User.V20221227.schemaName
        public static let space: String? = Security.User.V20221227.spaceName

        @ID
        var id: UUID?

        // Optional given/family name split out separately from the combined display `name`.
        @OptionalField(key: Security.User.V20230818.firstName)
        var firstName: String?

        @OptionalField(key: Security.User.V20230818.lastName)
        var lastName: String?

        @Field(key: Security.User.V20221227.name)
        var name: String

        @Field(key: Security.User.V20221227.username)
        var username: String

        // The Bcrypt-hashed password (never the plaintext) and the confirmed login email.
        @Field(key: Security.User.V20221227.password)
        var password: String

        @Field(key: Security.User.V20221227.email)
        var email: String

        // Holds a pending new email address until the user confirms it via a
        // ConfirmationToken; `email` itself is only updated once confirmed.
        @OptionalField(key: Security.User.V20230818A.unconfirmedEmail)
        var unconfirmedEmail: String?

        @Field(key: Security.User.V20221227.role)
        var role: UserRole

        // When the account's email was confirmed, and Fluent-managed lifecycle timestamps
        // (createdAt/updatedAt set automatically; deletedAt enables Fluent soft-deletes).
        @OptionalField(key: Security.User.V20230316.confirmedAt)
        var confirmedAt: Date?

        @Timestamp(key: Security.User.V20221227.createdAt, on: .create)
        var createdAt: Date?

        @Timestamp(key: Security.User.V20221227.updatedAt, on: .update)
        var updatedAt: Date?

        @Timestamp(key: Security.User.V20221227.deletedAt, on: .delete)
        var deletedAt: Date?

        /// Empty initializer required by Fluent so it can hydrate instances from the database.
        init() {}

        /// Creates a new user with a single combined display name (no separate first/last).
        /// - Parameters:
        ///   - id: Optional pre-assigned identifier; normally left `nil` and generated by the database.
        ///   - name: The display name.
        ///   - username: The unique login username.
        ///   - email: The account's email address.
        ///   - role: Initial ``Security/UserRole``; defaults to `.nonConfirmed` since new accounts
        ///     start unverified.
        init(
            id: UUID? = nil,
            name: String,
            username: String,
            email: String,
            role: Security.UserRole = .nonConfirmed
        ) {
            self.name = name
            self.username = username
            self.email = email
            self.role = role
        }

        /// Creates a new user from separate first/last names, deriving the combined `name`
        /// as `"\(firstName) \(lastName)"`.
        /// - Parameters:
        ///   - id: Optional pre-assigned identifier; normally left `nil` and generated by the database.
        ///   - firstName: Given name.
        ///   - lastName: Family name.
        ///   - username: The unique login username.
        ///   - email: The account's email address.
        ///   - role: Initial ``Security/UserRole``; defaults to `.nonConfirmed` since new accounts
        ///     start unverified.
        init(
            id: UUID? = nil,
            firstName: String,
            lastName: String,
            username: String,
            email: String,
            role: Security.UserRole = .nonConfirmed
        ) {
            self.firstName = firstName
            self.lastName = lastName
            self.username = username
            self.email = email
            self.role = role

            self.name = "\(firstName) \(lastName)"
        }
    }
}

extension Security.User {
    /// DTO representing a user's own detailed profile (e.g. for an "account settings" page):
    /// everything a user is allowed to see about themselves, but never the password hash.
    final class Profile: Content {
        let id: UUID
        let name: String
        let firstName: String
        let lastName: String
        let username: String
        let email: String
        let role: Security.UserRole
        let createdAt: Date

        /// Creates a profile view from already-extracted field values.
        /// - Parameters:
        ///   - id: The user's identifier.
        ///   - name: Combined display name.
        ///   - firstName: Given name (empty string if not set).
        ///   - lastName: Family name (empty string if not set).
        ///   - username: Login username.
        ///   - email: Email address.
        ///   - role: Current ``Security/UserRole``.
        ///   - createdAt: When the account was created.
        init(
            id: UUID,
            name: String,
            firstName: String,
            lastName: String,
            username: String,
            email: String,
            role: Security.UserRole,
            createdAt: Date
        ) {
            self.id = id
            self.name = name
            self.firstName = firstName
            self.lastName = lastName
            self.username = username
            self.email = email
            self.role = role
            self.createdAt = createdAt
        }
    }

    /// Converts this database model into the safe-to-serialize ``Security/User/Profile`` DTO.
    /// - Returns: A ``Security/User/Profile`` copying this user's public/self-visible fields.
    func convertToProfile() -> Security.User.Profile {
        Security.User.Profile(
            id: id!,
            name: name,
            firstName: firstName ?? "",
            lastName: lastName ?? "",
            username: username,
            email: email,
            role: role,
            createdAt: createdAt!
        )
    }
}

extension Security.User {
    /// DTO representing the minimal, safe-to-share view of a user shown to other users
    /// (e.g. in author bylines or user lists) — no email, no password hash.
    final class Public: Content {
        let id: UUID
        let name: String
        let username: String
        let role: Security.UserRole

        /// Creates a public view from already-extracted field values.
        /// - Parameters:
        ///   - id: The user's identifier.
        ///   - name: Combined display name.
        ///   - username: Login username.
        ///   - role: Current ``Security/UserRole``.
        init(id: UUID, name: String, username: String, role: Security.UserRole) {
            self.id = id
            self.name = name
            self.username = username
            self.role = role
        }
    }

    /// Converts this database model into the safe-to-serialize ``Security/User/Public`` DTO.
    /// - Returns: A ``Security/User/Public`` copying this user's publicly visible fields.
    func convertToPublic() -> Security.User.Public {
        Security.User.Public(id: id!, name: name, username: username, role: role)
    }
}

extension Security.User {
    /// Sets a new password after checking it was entered twice identically, hashing it with
    /// Bcrypt before storing (the plaintext password is never persisted).
    /// - Parameters:
    ///   - password: The new plaintext password.
    ///   - passwordConfirmation: A repeat of the new password, must match `password`.
    /// - Throws: ``Security/UserError/passwordsDoNotMatch`` if the two values differ.
    func setPassword(_ password: String, confirm passwordConfirmation: String) throws {
        if password != passwordConfirmation {
            throw Abort(
                .badRequest, reason: Security.UserError.passwordsDoNotMatch.errorDescription)
        }

        self.password = try Bcrypt.hash(password)
    }

    /// Updates the user's first/last name and re-derives the combined display `name`.
    /// - Parameters:
    ///   - firstName: New given name.
    ///   - lastName: New family name.
    func updateName(firstName: String, lastName: String) {
        self.firstName = firstName
        self.lastName = lastName
        self.name = "\(firstName) \(lastName)"
    }
}

/// Conformance to Vapor's `ModelAuthenticatable`, which wires this model into Vapor's
/// username/password (Basic Auth) authentication middleware: given a username and password
/// from an incoming request, Vapor looks up the matching `Security.User` row and calls
/// `verify(password:)` below to check the credentials.
extension Security.User: ModelAuthenticatable {
    /// Key path telling Vapor which field holds the login username.
    static var usernameKey: KeyPath<Security.User, Field<String>> {
        \Security.User.$username
    }

    /// Key path telling Vapor which field holds the Bcrypt password hash.
    static var passwordHashKey: KeyPath<Security.User, Field<String>> {
        \Security.User.$password
    }

    /// Checks a plaintext password against this user's stored Bcrypt hash, but only for
    /// active accounts — banned, deactivated, or unconfirmed users are rejected outright
    /// regardless of whether the password is correct.
    /// - Parameter password: The plaintext password to verify.
    /// - Returns: `true` if the password matches the stored hash.
    /// - Throws: ``Security/UserError/userNotActive`` if `active()` is `false`.
    func verify(password: String) throws -> Bool {
        guard self.active() else {
            throw Abort(.unauthorized, reason: Security.UserError.userNotActive.errorDescription)
        }
        return try Bcrypt.verify(password, created: self.password)
    }
}

/// Convenience conversions for collections of users, so a whole query result can be mapped
/// to its DTO form in one call instead of a manual `.map`.
extension Collection where Element: Security.User {
    /// Converts every element to its ``Security/User/Public`` DTO.
    /// - Returns: The public views, in the same order.
    func convertToPublic() -> [Security.User.Public] {
        return self.map { $0.convertToPublic() }
    }

    /// Converts every element to its ``Security/User/Profile`` DTO.
    /// - Returns: The profile views, in the same order.
    func convertToProfile() -> [Security.User.Profile] {
        return self.map { $0.convertToProfile() }
    }
}
