//
//  ServersController.swift
//  mul-api
//
//  Created by Richard Hancock on 12/29/25.
//
// Only here to support transition to new API system for Announcement system
/// Legacy top-level `/servers` route collection used by MegaMek game clients to
/// "announce" themselves so they show up in a public server list — e.g. a running
/// MegaMek dedicated server periodically POSTs its address/port/player count here.
/// Registered directly from `routes.swift` (not nested under `/api` or
/// `/battletech`); kept during the transition to the versioned
/// ``Api/V1/ServersController``.

import Fluent
import Vapor

/// A Vapor `RouteCollection` for the legacy server-announce endpoints.
struct ServersController: RouteCollection {
    /// Groups routes under `/servers`: `GET /` (list) and `POST /announce`
    /// (create-or-update).
    ///
    /// - Parameter routes: The `RoutesBuilder` to register routes on.
    /// - Throws: Does not currently throw; matches Vapor's `boot(routes:)`
    ///   signature.
    func boot(routes: any RoutesBuilder) throws {
        let servers = routes.grouped("servers")
        servers.get(use: index).description("Get A List Of Servers")
        servers.post("announce", use: create).description("Add/Update A Server To The List")
    }

    /// Serves `GET /servers`.
    ///
    /// - Parameter req: The incoming `Request`.
    /// - Returns: Every ``MegaMek/Server`` row currently in the database, as JSON
    ///   (unpaginated) — the public server list MegaMek clients display.
    /// - Throws: Rethrows errors from the database query.
    func index(req: Request) async throws -> [MegaMek.Server] {
        return try await MegaMek.Server.query(on: req.db).all()
    }

    /// Serves `POST /servers/announce`. A MegaMek server calls this (typically on
    /// a timer) to register itself or refresh its listing.
    ///
    /// Decodes a ``MegaMek/ServerDTO`` from the request body and determines the
    /// caller's IP from the TCP connection (`req.peerAddress`) rather than trusting
    /// a client-supplied address. If the DTO includes a `key` matching an existing
    /// server, that server's row is updated in place; otherwise a new server row is
    /// created (its key is generated by the model).
    ///
    /// - Parameter req: The incoming `Request`; its body must decode as
    ///   ``MegaMek/ServerDTO`` (port, optional password flag, connected users,
    ///   version, optional phase/MOTD, and an optional existing `key`).
    /// - Returns: The server's `serverKey`, so the caller can include it on
    ///   subsequent announce calls to update the same listing instead of creating
    ///   duplicates.
    /// - Throws: `Abort(.badRequest)` if the client's IP address cannot be
    ///   determined; rethrows errors from decoding the body or from the database
    ///   query/save.
    func create(req: Request) async throws -> String {
        let dto = try req.content.decode(MegaMek.ServerDTO.self)

        guard let ipAddress = req.peerAddress?.ipAddress else {
            throw Abort(.badRequest, reason: "Unable to determine client IP address")
        }

        let passworded = dto.passworded ?? false
        let users = dto.users.joined(separator: ", ")

        var existing: MegaMek.Server?
        if let key = dto.key {
            existing = try await MegaMek.Server.query(on: req.db)
                .filter(\.$serverKey == key)
                .first()
        }

        let server: MegaMek.Server
        if let existing {
            existing.ipAddress = ipAddress
            existing.port = dto.port
            existing.passworded = passworded
            existing.users = users
            existing.version = dto.version
            existing.phase = dto.phase ?? existing.phase
            existing.motd = dto.motd
            server = existing
        } else {
            server = MegaMek.Server(
                port: dto.port,
                ipAddress: ipAddress,
                passworded: passworded,
                users: users,
                version: dto.version,
                phase: dto.phase ?? "",
                motd: dto.motd
            )
        }

        try await server.save(on: req.db)

        return server.serverKey
    }
}
